[project]
name = 'clarity-test-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.integer-overflow]
path = 'contracts/integer-overflow.clar'
clarity_version = 2
epoch = 2.5

[contracts.pow-with-neg-exp]
path = 'contracts/pow-with-neg-exp.clar'
clarity_version = 2
epoch = 2.5

[contracts.quadratic-equation]
path = 'contracts/quadratic-equation.clar'
clarity_version = 2
epoch = 2.5

[contracts.signed-integer-overflow]
path = 'contracts/signed-integer-overflow.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
